<div class="picture"><img src='<?php echo $this->getViewFileUrl('images/1.jpeg'); ?>' alt="photo"></div>
<div class="picture"><img src='<?php echo $this->getViewFileUrl('images/2.jpeg'); ?>' alt="photo"></div>
<div class="picture"><img src='<?php echo $this->getViewFileUrl('images/3.jpeg'); ?>' alt="photo"></div>

<script type="text/x-magento-init">
    {
        ".picture": {
            "jqueryWidget": {}
        }
    }
 </script>
