<ul class="menu">
    <li class="menu__item"><a href="men.html" class="menu__link">Mens</a></li>
    <li class="menu__item"><a href="women.html" class="menu__link">Womens</a></li>
    <li class="menu__item"><a href="gear.html" class="menu__link">Gear</a></li>
    <li class="menu__item"><a href="training.html" class="menu__link">Training</a></li>
    <li class="menu__item"><a href="sale.html" class="menu__link">Sale</a></li>
</ul>
