<div id="ui-rendering-xml" data-bind="scope:'ui-rendering-xml'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div class="test"></div>
<script type="text/x-magento-init">
    {
        "*" :{
           "objectEditor": {},
           "dataPassing": {},
           "Magento_Ui/js/core/app": {
                "components": {
                    "ui-creator": {
                        "component": "Magento_Theme/js/ui-creator"
                    }
                }
           }
        }
    }
 </script>
